site_name: Rudist
site_description: Redis GUI Client built with Rust and egui with AI
site_url: https://github.com/davelet/redis-egui-client
repo_url: https://github.com/davelet/redis-egui-client

theme:
  name: material
  palette:
    - primary: blue

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - AI Configuration: ai_configuration.md
  - Changelog: changelog.md

plugins:
  - search

docs_dir: docs
site_dir: public
