[package]
name = "e-client-config"
version = "1.0.0"
edition = "2024"

[dependencies]
e-client-bilingual = { path = "../e-client-bilingual" }
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6.0.0"
toml = "0.9.10"
redis = { version = "1.0.2", features = ["json"] }

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3.6.2", features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.6.2", features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3.6.2", features = ["sync-secret-service"] }

[dev-dependencies]
serde_json = "1.0"
