[package]
name = "Rudist"
version = "0.4.6"
edition = "2024"
repository = "https://github.com/davelet/redis-egui-client"
authors = ["Sheldon.Wei<sheldon.sh.hb@gmail.com>"]
readme = "README.md"
description = "A AI-agent Redis GUI client built with egui + rig-core"
categories = ["gui"]
keywords = ["redis", "egui", "eframe", "gui"]

[dependencies]
e-client-core = { path = "../e-client-core" }
e-client-config = { path = "../e-client-config" }
e-client-basics = { path = "../e-client-basics" }
e-client-logging = { path = "../e-client-logging" }
egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["default"] }
eframe = { version = "0.33.3", default-features = false, features = [
    "default_fonts",
    "glow",
    "wgpu",
] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
image = "0.25.9"
wgpu = { version = "27", features = ["metal", "dx12"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
pulldown-cmark = "0.12"

[build-dependencies]
winres = "0.1.12"
[package.metadata.bundle]
name = "Rudist"
identifier = "com.sheldon.client.rudist"
icon = ["assets/icon.icns"]
category = "public.app-category.developer-tools"
short_description = "A small Redis GUI client built with egui/eframe"

[package.metadata.bundle.macOS]
entitlements = "entitlements.plist"

[package.metadata.wix]
upgrade-guid = "7B341871-490E-44C5-BE5B-9BDE6D84A371"
path-guid = "11E8DDEE-AA89-406C-9A09-8558E7D5BE88"
license = false
eula = false

[package.metadata.packager]
product-name = "Rudist"
identifier = "com.sheldon.client.rudist"
version = "0.4.2"
category = "DeveloperTool"
publisher = "Sheldon.Wei"
homepage = "https://github.com/davelet/redis-egui-client"
icons = ["../assets/icon.icns"]

[[package.metadata.packager.binaries]]
main = true
path = "Rudist"

[package.metadata.packager.macos]
minimum-system-version = "10.13"
entitlements = "entitlements.plist"

[package.metadata.packager.dmg]
app-position = [180, 170]
application-folder-position = [360, 170]
window-size = [600, 400]
